name: mms_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.12.29
  chat_bubbles:
  csv: ^5.0.2
  dio: ^5.3.2
  external_path: ^1.0.3
  ffmpeg_kit_flutter_full_gpl: 4.5.1
  file_picker: ^5.2.5
  flutter_downloader: 1.10.4
  flutter_native_image: ^0.0.6+1
  flutter_screenutil: ^5.7.0
  flutter_spinkit: ^5.2.0
  flutter_svg:
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.6.0
  global_configuration: ^2.0.0-nullsafety.1
  google_fonts: 4.0.4
  hive_flutter: ^1.1.0
  image_cropper: ^3.0.2
  image_picker: ^1.0.0
  intl: ^0.18.1
  logger: ^1.3.0
  open_filex: ^4.3.2
  path_provider: ^2.0.15
  pdf: 3.10.4
  percent_indicator: ^4.2.3
  permission_handler: ^10.4.3
  pin_code_fields: ^8.0.1
  pretty_qr_code: ^2.0.3
  provider: ^6.0.5
  share_plus: ^6.3.1
  timeago: ^3.5.0
  watcher: ^1.0.2
  video_viewer:
    git:
      url: https://github.com/ologunB/video_viewer.git
      ref: main
  sodium_libs:
    git:
      url: https://github.com/ologunB/sodium_libs.git
      ref: main

dev_dependencies:
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  color: "#A8CF45"
  image: assets/images/shield_logo.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/cfg/
